// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKxfXazfX1R59LKPicCtZ70dqEa4caRVw',
    appId: '1:676178387175:web:58bb03dcc50f9133ed4242',
    messagingSenderId: '676178387175',
    projectId: 'fraps-b0c0f',
    authDomain: 'fraps-b0c0f.firebaseapp.com',
    storageBucket: 'fraps-b0c0f.firebasestorage.app',
    measurementId: 'G-B94Q7T4CNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0JDXU-v3xDSXj2c1kqHy_IfFGozIcBZM',
    appId: '1:676178387175:android:88b6cdc1ad897c4fed4242',
    messagingSenderId: '676178387175',
    projectId: 'fraps-b0c0f',
    storageBucket: 'fraps-b0c0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXyX_n72-p-u1xKnW55W0JFuqILthg1ZE',
    appId: '1:676178387175:ios:45bb9f9703505f21ed4242',
    messagingSenderId: '676178387175',
    projectId: 'fraps-b0c0f',
    storageBucket: 'fraps-b0c0f.firebasestorage.app',
    iosBundleId: 'com.example.firstMapsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXyX_n72-p-u1xKnW55W0JFuqILthg1ZE',
    appId: '1:676178387175:ios:45bb9f9703505f21ed4242',
    messagingSenderId: '676178387175',
    projectId: 'fraps-b0c0f',
    storageBucket: 'fraps-b0c0f.firebasestorage.app',
    iosBundleId: 'com.example.firstMapsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKxfXazfX1R59LKPicCtZ70dqEa4caRVw',
    appId: '1:676178387175:web:80d2fd17e4638718ed4242',
    messagingSenderId: '676178387175',
    projectId: 'fraps-b0c0f',
    authDomain: 'fraps-b0c0f.firebaseapp.com',
    storageBucket: 'fraps-b0c0f.firebasestorage.app',
    measurementId: 'G-1LLT02XP4F',
  );
}
